/** Keys a hero chip can point at. */
export const heroSnippets = [
	"fields",
	"tables",
	"actions",
	"panels",
	"palette",
	"notifications",
	"locales",
	"extend",
] as const;

export type HeroSnippet = (typeof heroSnippets)[number];

export const SNIPPET_CODE: Record<HeroSnippet, { file: string; lines: string[] }> = {
	fields: {
		file: "app/Admin/Pages/CustomersPage.php",
		lines: [
			"$s->select('city_id')->label('City')",
			"    ->dependsOn('country_id')",
			"    ->query(fn (array $deps, string $search) =>",
			"        City::query()",
			"        ->where('country_id', $deps['country_id'])",
			"        ->where('name', 'like', \"%{$search}%\")",
			"        ->limit(20)->pluck('name', 'id')->all())",
			"    ->creatable(",
			"        [$s->text('name')->required()],",
			"        fn (array $data) => [",
			"            'value' => City::create($data)->id,",
			"            'label' => $data['name']],",
			"    ),",
		],
	},
	tables: {
		file: "app/Admin/Pages/OrdersPage.php",
		lines: [
			"$s->table('orders')",
			"    ->query(fn () => Order::query())",
			"    ->tabs([",
			"        Tab::make('all')->label('All'),",
			"        Tab::make('unpaid')->label('Unpaid')",
			"            ->count()->query(fn ($q) =>",
			"                $q->whereNull('paid_at')),",
			"    ])",
			"    ->filters([Daterange::make('created_at')])",
			"    ->filtersIn('inline')",
			"    ->defaultSort('status')->groups('status')",
			"    ->paginate(25, [10, 25, 50]);",
		],
	},
	actions: {
		file: "app/Admin/Pages/OrdersPage.php",
		lines: [
			"$s->action('refund')->label('Refund')",
			"    ->icon('undo-2')->color('danger')",
			"    ->confirm('Refund this order?',",
			"        'Money is back in 3–5 days.')",
			"    ->handle(function (ActionCtx $ctx): Effects {",
			"        $order = Order::findOrFail(",
			"            $ctx->row['id']);",
			"        RefundOrder::dispatch($order);",
			"",
			"        return Effects::make()",
			"            ->notify('Refund queued')",
			"            ->refreshTable('orders');",
			"    }, needs: ['row']);",
		],
	},
	panels: {
		file: "app/Admin/VendorPanel.php",
		lines: [
			"class VendorPanel extends Panel",
			"{",
			"    public function configure(",
			"        PanelConfig $panel",
			"    ): PanelConfig {",
			"        return $panel",
			"            ->id('vendor')->prefix('vendor')",
			"            ->guard('vendor')",
			"            ->pages([OrdersPage::class,",
			"                PayoutsPage::class])",
			"            ->navigation('topbar')",
			"            ->density('compact')",
			"            ->brand('Vendor desk');",
			"    }",
			"}",
		],
	},
	palette: {
		file: "app/Admin/AdminPanel.php",
		lines: [
			"$panel->commandPalette(",
			"    fn (CommandPaletteConfig $p) => $p",
			"        ->placeholder('Jump to…')",
			"        ->commands([",
			"            Command::make('New order')",
			"                ->url('/admin/orders/new')",
			"                ->icon('plus')->group('Create'),",
			"            Command::make('Clear cache')",
			"                ->handler('cache:clear')",
			"                ->keywords(['flush', 'purge'])",
			"                ->group('Ops'),",
			"        ]));",
		],
	},
	notifications: {
		file: "app/Jobs/FlagOrder.php",
		lines: [
			"Notification::make()",
			"    ->title(",
			'        "Order #{$order->number} needs review")',
			"    ->body('Fraud score above threshold.')",
			"    ->warning()->icon('shield-alert')",
			"    ->actions([",
			"        NotificationAction::make('Open order')",
			'            ->url("/admin/orders/{$order->id}"),',
			"    ])",
			"    ->sendToDatabase(",
			"        User::role('finance')->get(),",
			"    );",
		],
	},
	locales: {
		file: "app/Admin/Pages/PostsPage.php",
		lines: [
			"$panel->locales(['en', 'uk', 'de'])",
			"    ->defaultLocale('en');",
			"",
			"// every translatable field gets a locale tab",
			"// in the editor",
			"$s->text('title')->translatable()",
			"    ->rulesForLocale('en', 'required|max:70')",
			"    ->rulesForLocale('de', 'max:80'),",
			"$s->richtext('body')->translatable(),",
			"$s->slug('slug')->fromField('title'),",
			"",
			"// the admin UI itself switches",
			"// with the same list",
			"$s->localeSwitcher(),",
		],
	},
	extend: {
		file: "resources/js/admin.tsx",
		lines: [
			"registerBlock({",
			"    kind: 'map-point',",
			"    behavior: 'field',",
			"    render: ({ ctx }) => (",
			"        <MapPicker",
			"            value={ctx.binding?.value}",
			"            onChange={ctx.binding?.onChange}",
			"            readOnly={ctx.surface === 'cell'}",
			"        />",
			"    ),",
			"});",
		],
	},
};
