#!/usr/bin/env tsx
/**
 * Fetches the 7 generated API reference files from DiVotek/tbtop at the
 * pinned tag and turns each into a Fumadocs MDX page under
 * content/docs/api/.
 *
 * Run via `npm run sync:api`. Never hand-edit the output — rerun this
 * script instead, after bumping PINNED_TAG in app/lib/shared.ts.
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { PINNED_TAG } from "../app/lib/shared";

const REPO = "DiVotek/tbtop";
const SOURCE_DIR = "docs/ai/api";
const OUTPUT_DIR = path.join(
	path.dirname(fileURLToPath(import.meta.url)),
	"..",
	"content",
	"docs",
	"api",
);

// name -> nav title, kept in the order the sidebar should show them.
const PAGES: Record<string, string> = {
	builder: "The S Builder",
	fields: "Fields",
	blocks: "Blocks",
	tables: "Tables",
	actions: "Actions",
	notifications: "Notifications",
	panel: "Panel",
};

const RAW_BASE = `https://raw.githubusercontent.com/${REPO}/${PINNED_TAG}/${SOURCE_DIR}`;
const GITHUB_BLOB_BASE = `https://github.com/${REPO}/blob/${PINNED_TAG}/docs/ai`;

const GENERATED_COMMENT_RE = /^<!--\s*GENERATED[\s\S]*?-->\n*/;

/** `[text](../README.md)` / `[text](../authoring-pages.md#anchor)` -> a GitHub blob link at the pinned tag. */
function rewriteGuideLinks(body: string): string {
	return body.replace(
		/\]\(\.\.\/([a-zA-Z0-9_-]+\.md)((?:#[^)]*)?)\)/g,
		(_match, file: string, anchor: string) => `](${GITHUB_BLOB_BASE}/${file}${anchor})`,
	);
}

/** `[text](./fields.md)` -> the matching page in this same API section. */
function rewriteSiblingApiLinks(body: string): string {
	return body.replace(
		/\]\(\.\/([a-zA-Z0-9_-]+)\.md((?:#[^)]*)?)\)/g,
		(_match, name: string, anchor: string) => `](/docs/api/${name}${anchor})`,
	);
}

/**
 * Table cells hold PHP-ish snippets with literal `{`/`}` and, once, a raw
 * `<dl>` tag — both of which MDX tries to parse as JSX. Escape them to
 * entities so the tables compile without changing what renders.
 */
function escapeMdxHazards(body: string): string {
	return body
		.split("\n")
		.map((line) => {
			if (!line.startsWith("|")) return line;
			return line
				.replace(/\{/g, "&#123;")
				.replace(/\}/g, "&#125;")
				.replace(/<(\/?[a-zA-Z])/g, "&lt;$1");
		})
		.join("\n");
}

function toMdx(name: string, title: string, raw: string): string {
	const withoutComment = raw.replace(GENERATED_COMMENT_RE, "");
	const lines = withoutComment.split("\n");

	// First non-empty paragraph after the "Back to the AI guide" blockquote
	// becomes the frontmatter description; drop the redundant `# Title` and
	// "Back to" lines from the body since Fumadocs renders the title itself.
	let i = 0;
	while (i < lines.length && !lines[i].startsWith("# ")) i++;
	i++; // past the heading
	while (i < lines.length && lines[i].trim() === "") i++;
	while (i < lines.length && lines[i].startsWith(">")) i++;
	while (i < lines.length && lines[i].trim() === "") i++;
	const description = (lines[i] ?? "").trim();

	let body = lines.slice(i).join("\n").trimStart();
	body = rewriteSiblingApiLinks(rewriteGuideLinks(body));
	body = escapeMdxHazards(body);

	// Frontmatter is plain text: strip markdown link syntax down to its
	// label, and backticks, rather than carrying markdown into YAML.
	const plainDescription = description
		.replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
		.replace(/\*\*([^*]+)\*\*/g, "$1")
		.replace(/`/g, "");
	const escapedDescription = plainDescription.replace(/"/g, '\\"');

	return `---
title: ${title}
description: "${escapedDescription}"
---

{/* Generated by \`npm run sync:api\` from tbtop/admin's docs/ai/api/${name}.md at ${PINNED_TAG}. Do not hand-edit — rerun the script instead. */}

${body}
`;
}

async function main() {
	await mkdir(OUTPUT_DIR, { recursive: true });

	for (const [name, title] of Object.entries(PAGES)) {
		const url = `${RAW_BASE}/${name}.md`;
		const res = await fetch(url);
		if (!res.ok) {
			throw new Error(`failed to fetch ${url}: ${res.status} ${res.statusText}`);
		}
		const raw = await res.text();
		const mdx = toMdx(name, title, raw);
		await writeFile(path.join(OUTPUT_DIR, `${name}.mdx`), mdx, "utf8");
		console.log(`wrote content/docs/api/${name}.mdx`);
	}

	const pages = Object.keys(PAGES)
		.map((name) => `"${name}"`)
		.join(", ");
	const metaJson = `{\n\t"title": "API Reference",\n\t"pages": [${pages}]\n}\n`;
	await writeFile(path.join(OUTPUT_DIR, "meta.json"), metaJson, "utf8");
	console.log("wrote content/docs/api/meta.json");
}

main().catch((error) => {
	console.error(error);
	process.exitCode = 1;
});
